version: '2.4'
services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./bin/dbinit:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready --host=db --user=postgres --dbname=abalone_development

  app: &app
    build: .
    image: abalone
    volumes:
      - .:/myapp
      - apptmp:/myapp/tmp
    depends_on:
      db:
        condition: service_healthy
  web:
    <<: *app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "127.0.0.1:3000:3000"
  delayed_job:
    <<: *app
    command: bundle exec rails jobs:work

volumes:
  dbdata:
  apptmp:
